### ISSUE TITLE
Port inline PDF viewer to securedrop.org

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop.org#674]
freedom.press has a nice inline PDF stream block type, as can be seen on this post:

https://freedom.press/news/freedom-press-foundation-releases-its-2019-impact-report/

It would be great to port this over to securedrop.org. If we do so, we need to test the widget's functionality (toolbar buttons) across browsers to ensure the CSP is configured correctly.

The use case are documents like whitepapers and audit reports.

**Comment by eloquence** [comment]
(Leaving in triage for now @harrislapiroff, not a super high priority but a "nice-to-have", we can discuss in next backlog review)

**Comment by harrislapiroff** [comment]
This sounds like a great feature to port over. My only specific comment is that, since we particularly encourage tor browser usage on securedrop.org we should have a more elegant noscript fallback than we do on freedom.press (and maybe we can port that fallback back to freedom.press!)

Currently freedom.press on Tor's "Safest" mode looks like:

![Screen Shot 2020-02-28 at 22 02 13](https://user-images.githubusercontent.com/296631/75590792-c3a68400-5a43-11ea-9e99-97b2c02fee38.png)

😬
