### ISSUE TITLE
Add custom delisted template for "extended downtime" case

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop.org#700]
The options for delisting a SecureDrop instance (in the settings for a directory entry) distinguish various reasons, such as "Non-200 status response" and "Extended downtime". However, all of those reasons appear to currently result in the same display on the directory entry, a page which says:

> Freedom of the Press Foundation routinely verifies that SecureDrop instances are up and running and follow best security practices. We have detected issues with this instance, and have temporarily removed it from the directory.

This language is problematic for a case where an instance has simply been down for maintenance for a while. That's why I don't use delisting at all right now in those cases, and instead unpublish them entirely -- which is not great, because it means folks will just get a 404 if they try to visit an entry they've gone to before.

I would suggest that we set up a template for that case, which would say something like:

> This instance is experiencing an extended service outage. We have temporarily removed it from the directory.

We can continue to use the other template for all other "delisted" reasons that are currently supported.

**Comment by prateekj117** [comment]
@eloquence Sounds good. Would like to work on this. I see there are following delisted reasons:
```
DELISTED_REASONS = (
    ('http', 'Mixed-content or no HTTPS'),
    ('no200', 'Non-200 status response'),
    ('down', 'Extended downtime (>1 week)'),
    ('other', 'Other'),
)

```
Should we treat `other` as a criterion for judging if an instance is down for maintenance or should we maybe add another delisted reason for this.

**Comment by harrislapiroff** [comment]
Hm. I was going to suggest that maybe we should add a freeform field for downtime message, but since we do already have those delisted reasons, let's try using them for now. Let's do the following:

- [ ] Interpret `down` as criterion for displaying that message
- [ ] Remove the parenthetical `(>1 week)` from the verbose text of that reason. We should let the SD team decide their criteria for this
- [ ] Leave messaging for other reasons intact as is

@prateekj117 are you still hoping to work on this one?

**Comment by prateekj117** [comment]
@harrislapiroff Sounds good. Yes, I will file a PR within next week.
