### ISSUE TITLE
Analytics loaded over HTTP on onion site

### ISSUE THREAD

**Issue by maeve-fpf** [freedomofpress/securedrop.org#754]
Pages on the SecureDrop site contain:

    <noscript><p><img src="//analytics.freedom.press/piwik.php?idsite=3" style="border:0;" alt="" /></p></noscript>

Because the onion address is http:// rather than https://, this can load http://analytics.freedom.press. That causes a mixed-content warning in the "Safest" security level of Tor Browser since JavaScript is disabled. Can we fix that URL to use https:// ?

**Comment by SaptakS** [comment]
So I looked into this issue a bit. Seems like this entire link is being generated by [django-analytical](https://django-analytical.readthedocs.io/en/latest/services/piwik.html) based on the `PIWIK_DOMAIN_PATH` and `PIWIK_SITE_ID` that we set in the settings file. I did try to add the https:// scheme to the `PIWIK_DOMAIN_PATH` but the code doesn't expect a scheme and hence throws an error. So as I understand, we don't have much straightforward control on django-analytical will generate the link.

Also, a point to note here, according to the documentation piwik is deprecated and now replaced by matomo in django-analytical. Not that it helps related to this issue, but maybe a point worth noting and looking into.

**Comment by conorsch** [comment]
@SaptakS Nice finds! You're right that we should be using the "Matomo" nomenclature everywhere, not Piwik. In terms of forcing HTTPS, looks like we'll need to PR into the upstream module:

https://github.com/jazzband/django-analytical/blob/master/analytical/templatetags/matomo.py#L32

The embedded JS code block hardcodes `src="//%(url)s`, so it'll always be HTTP when over an HTTP onion, but we want the ability to force HTTPS always. Is there perhaps some way in Django/Python to override the `TRACKING_CODE` var in our settings files? If so, that'd provide clean resolution. But perhaps a PR/fork is the more friendly thing to do.

**Comment by harrislapiroff** [comment]
Yeah, I wonder if we could do some runtime monkey patching to make this work. I feel like @chigby has maybe done stuff like this in the past?

@conorsch Is there any concern that we shouldn't be using analytics at all on onion users? Does it compromise the security of using an onion service if the page includes calls to non-onion assets? This is outside my technical knowledge—just want to double-check before we go deep down that rabbit hole.

**Comment by harrislapiroff** [comment]
(If runtime monkey patching is possible, the place to do it would probably be in `common.apps.CommonConfig.__init__` file)

**Comment by harrislapiroff** [comment]
Assuming we still want analytics, I think we're going to solve this by getting rid of our dependency on django-analytical and just writing the tracking code ourselves. We're not actually getting a huge amount of benefit from django-analytical and we've run into a few annoyances with it.

**Comment by conorsch** [comment]
> Is there any concern that we shouldn't be using analytics at all on onion users? Does it compromise the security of using an onion service if the page includes calls to non-onion assets? 

No strong concerns on this front. We already encourage the use of Tor overall, both on the securedrop.org website, and on other FPF-run websites. Providing an Onion service as a first-class supported service is part and parcel to ensuring user privacy: the user's traffic is bypasses intermediaries that would otherwise be in the loop via clearnet access.Yes, there are clearnet assets pulled in, but I'm marginally more concerned about the media/static files from a storage bucket (https://github.com/freedomofpress/securedrop.org/pull/736). Even still, those fetches themselves are always performed over Tor, and additionally over HTTPS. The one notable exception to the HTTPS rule is what motivated opening this issue!

The reason we self-host Matomo, rather than use more popular analytics platforms, is specifically to reduce third-parties involved in our (rather barebones) analytics, and because the software respects DoNotTrack requests—for whatever that's worth, given that Tor Browser [doesn't put much stock in those protections](https://blog.torproject.org/improving-private-browsing-modes-do-not-track-vs-real-privacy-design), users can explicitly say "nope" regardless of whether using clearnet or tor, and we'll honor it. Finally, if tor browser users follow the guidance on our site, the JS won't run anyway! Mostly I'm interested in a baseline of privacy that we can reuse across multiple sites, on both clearnet and Onion, as an example of practicing what we preach. 

> just writing the tracking code ourselves

Your call! Based on https://developer.matomo.org/guides/tracking-javascript-guide it doesn't look terribly complicated to embed. Given the questions above, is there a way to alter behavior of the embed based on Host info? I don't see as a requirement, but interested in what's possible there—useful even in staging environments, I'd expect. All we need config wise is 1) a matomo url, and 2) a site_id. Everywhere else looks consistent with the stock config.

**Comment by harrislapiroff** [comment]
Thanks for the thorough response @conorsch. I'm satisfied with this approach then:

* Remove `django-analytical` as a dependency
* Add the code manually to the template (pulling site id and domain from settings, the same way `django-analytical` does)
* Have the code *always* us https (it is theoretically possible to vary the behavior based on the host, but I can't think of any circumstances under which we'd like to serve via http)
